spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://18.143.46.88:31672/postgres
        username: admin
        password: m9NUOgb7xi6M3TKjstcHPXSF8EosmcJC

    jpa:
#        properties:
#            hibernate:
#                format_sql: 'true'
        show-sql: 'true'
