spring:
  mvc:
    throw-exception-if-no-handler-found: true
  profiles:
    active: me

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG